### ISSUE TITLE
Cannot find module puppeteer

### ISSUE THREAD

**Issue by tjlillo** [agusalex/modemReboot#3]
This is for the unraid CA. I got my script running well outside unraid, but in the Docker the script never makes it past the requires and throws Error: Cannot find module 'puppeteer'

**Comment by tjlillo** [comment]
Full log:

Starting Modem Rebooter...
Crontab Not Present:
Reboot Started at Mon Oct 19 17:40:44 CDT 2020
internal/modules/cjs/loader.js:638
throw err;
^

Error: Cannot find module 'puppeteer'

at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (internal/modules/cjs/helpers.js:25:18)
at Object.<anonymous> (/myscripts/netgear.js:1:19)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by agusalex** [comment]
Hey @tjlillo sorry for the delay, this was a hectic year, to say the least, but now I'll have some time for my side projects.
That's really weird, did you manage to get it working? Could you paste the code of your script here so that I can test that out?

**Comment by tjlillo** [comment]
I already deleted the app and the script, unfortunately. Thanks for getting back to me though.

**Comment by agusalex** [comment]
No probs, do let me know if you want to try that again! Cheers!
